// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR2ckb9DlNliCL0l8S_3xvXCVGXwuIvVY',
    appId: '1:506140181003:web:c7a6a34e8a4e456ced7d0e',
    messagingSenderId: '506140181003',
    projectId: 'bakibuilders',
    authDomain: 'bakibuilders.firebaseapp.com',
    databaseURL: 'https://bakibuilders-default-rtdb.firebaseio.com',
    storageBucket: 'bakibuilders.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOWXaIsOU_VbVnPMfCpy8Tlv-GZw1WT3E',
    appId: '1:506140181003:android:fc14442357636da9ed7d0e',
    messagingSenderId: '506140181003',
    projectId: 'bakibuilders',
    databaseURL: 'https://bakibuilders-default-rtdb.firebaseio.com',
    storageBucket: 'bakibuilders.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA98vlT3Z5A52WPpvoO5KIrl19TvU5tfwY',
    appId: '1:506140181003:ios:54798e9c47150b79ed7d0e',
    messagingSenderId: '506140181003',
    projectId: 'bakibuilders',
    databaseURL: 'https://bakibuilders-default-rtdb.firebaseio.com',
    storageBucket: 'bakibuilders.appspot.com',
    iosClientId: '506140181003-3ofd0hc3td8ed40vli73rhmjjk3u93kd.apps.googleusercontent.com',
    iosBundleId: 'com.example.bakiBuilders',
  );
}
